---
- hosts: all:!appliance
  tasks:
    - name: Install container runtime
      include_role:
        name: "ensure-{{ (container_command == 'docker') | ternary('docker', 'podman') }}"

    - when: ansible_distribution != 'Fedora'
      block:
        # note(pabelanger): we force docker until we can figure out podman ipv6 issue
        - name: install docker runtime
          when: buildset_registry is not defined
          include_role:
            name: ensure-docker
        - name: run buildset registry (if not already running)
          when: buildset_registry is not defined
          include_role:
            name: run-buildset-registry
          vars:
            container_command: docker

    - when: ansible_distribution == 'Fedora'
      block:
        # note(pabelanger): we force docker until we can figure out podman ipv6 issue
        - name: install docker runtime
          when: buildset_registry is not defined
          include_role:
            name: ensure-podman
        - name: run buildset registry (if not already running)
          when: buildset_registry is not defined
          include_role:
            name: run-buildset-registry
          vars:
            container_command: podman

    - name: Use buildset registry
      include_role:
        name: use-buildset-registry

- hosts: localhost
  tasks:
    - name: Run pull-from-intermediate-registry role
      include_role:
        name: pull-from-intermediate-registry
